require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/LineLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 20

RSpec/Capybara/FeatureMethods:
  Enabled: false